default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    args: [--unsafe]
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude_types:
      - "markdown"
  - id: check-ast
  - id: debug-statements
  - id: check-docstring-first
  - id: check-toml

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade
      args: [--py37-plus]

- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.2
  hooks:
    - id: pycln
      args: [--all]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.5
  hooks:
    - id: ruff
      args: ["--extend-select=I,UP", "--fix"]
    - id: ruff-format
