"""update schema

Revision ID: 05c9b11c5617
Revises: bfb2af419d79
Create Date: 2024-04-16 03:19:20.463355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05c9b11c5617"
down_revision: Union[str, None] = "bfb2af419d79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("video", sa.Column("url", sa.String(), nullable=True))
    op.alter_column("video", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("video", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("video", "duration", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("video", "language", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "video",
        "transcription",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_index("ix_video_youtube_url", table_name="video")
    op.create_index(op.f("ix_video_url"), "video", ["url"], unique=True)
    op.drop_column("video", "youtube_url")
    op.drop_column("video", "tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video", sa.Column("tags", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "video",
        sa.Column("youtube_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_video_url"), table_name="video")
    op.create_index("ix_video_youtube_url", "video", ["youtube_url"], unique=True)
    op.alter_column(
        "video",
        "transcription",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("video", "language", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("video", "duration", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("video", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("video", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("video", "url")
    # ### end Alembic commands ###
