"""add category

Revision ID: 0e0ad1c06063
Revises: 23eb8c93fd16
Create Date: 2024-04-27 23:31:17.217494

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e0ad1c06063"
down_revision: str | None = "23eb8c93fd16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("video", sa.Column("category", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "category")
    # ### end Alembic commands ###
