"""use association model instead of table

Revision ID: 4dd3884e3384
Revises: e280247e6ae1
Create Date: 2024-05-10 20:01:28.863768

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dd3884e3384"
down_revision: str | None = "e280247e6ae1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("favorite", "updated_at")
    op.drop_column("favorite", "deleted_at")
    op.drop_index("ix_playlist_id", table_name="playlist")
    op.drop_column("playlist", "deleted_at")
    op.drop_index("ix_playlist_video_playlist_id", table_name="playlist_video")
    op.drop_index("ix_playlist_video_video_id", table_name="playlist_video")
    op.drop_column("playlist_video", "updated_at")
    op.drop_column("playlist_video", "deleted_at")
    op.drop_column("user", "deleted_at")
    op.drop_column("video", "deleted_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video",
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "playlist_video",
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "playlist_video",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_playlist_video_video_id", "playlist_video", ["video_id"], unique=False
    )
    op.create_index(
        "ix_playlist_video_playlist_id", "playlist_video", ["playlist_id"], unique=False
    )
    op.add_column(
        "playlist",
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.create_index("ix_playlist_id", "playlist", ["id"], unique=False)
    op.add_column(
        "favorite",
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "favorite",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
