"""add related content

Revision ID: 9e5ca07a22eb
Revises: 6c43fee2e8d6
Create Date: 2024-05-30 14:56:36.588333

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e5ca07a22eb"
down_revision: str | None = "6c43fee2e8d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video",
        sa.Column(
            "related_content", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "related_content")
    # ### end Alembic commands ###
