"""attribute user to video

Revision ID: a23d5aace1a6
Revises: ed52319e3b33
Create Date: 2024-05-06 22:59:37.491630

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a23d5aace1a6"
down_revision: str | None = "ed52319e3b33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("video", sa.Column("user_id", sa.String(), nullable=True))
    op.create_foreign_key(None, "video", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "video", type_="foreignkey")
    op.drop_column("video", "user_id")
    # ### end Alembic commands ###
