"""create playlist relation

Revision ID: d7a089944eb3
Revises: 791389c40fb7
Create Date: 2024-05-03 00:31:44.689203

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7a089944eb3"
down_revision: str | None = "791389c40fb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playlist_id"), "playlist", ["id"], unique=False)
    op.create_table(
        "playlist_video",
        sa.Column("playlist_id", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
        ),
        sa.PrimaryKeyConstraint("playlist_id", "video_id"),
    )
    op.create_index(
        op.f("ix_playlist_video_playlist_id"),
        "playlist_video",
        ["playlist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playlist_video_video_id"), "playlist_video", ["video_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_playlist_video_video_id"), table_name="playlist_video")
    op.drop_index(op.f("ix_playlist_video_playlist_id"), table_name="playlist_video")
    op.drop_table("playlist_video")
    op.drop_index(op.f("ix_playlist_id"), table_name="playlist")
    op.drop_table("playlist")
    # ### end Alembic commands ###
